### ISSUE TITLE
Update to newer purescript?

### ISSUE THREAD

**Issue by dbaynard** [Thimoteus/literate-purescript#1]
I see 48 errors with `purs` 0.11.6, `node` 8.8.1. Is this library still maintained, and would PRs be received?

**Comment by Thimoteus** [comment]
I was thinking about revisiting this and changing the scope of what code is accepted to just be triple-backticks, and incorporating [optlicative](https://github.com/Thimoteus/purescript-optlicative). It hasn't been maintained, but I think I'll revisit it soon.

**Comment by paluh** [comment]
I've done upgrade for PS-0.12. It is nearly ready for PR:

https://github.com/Thimoteus/literate-purescript/compare/master...paluh:master
